#!/usr/bin/env python3
"""RPC return-contract snapshot — CHECK 11 of cross_check.sh (D-RPC-CONTRACT-SYNC-01).

Extracts the json[b]_build_object key set of every rpc_* function across the canonical
SQL files (later definition wins — mirrors PostgreSQL apply order and L-1 semantics)
and diffs it against a committed snapshot. A changed return shape must ship with its
doc sync (Dok 6 / EngSpec + DECISIONS_LOG) in the SAME PR — this check makes the
drift visible instead of relying on discipline (Slice8 §2.2 / ARS-279 incident).

Usage:
  contract_snapshot.py check  <snapshot-file> <sql-file>...   # diff, exit 1 on drift
  contract_snapshot.py update <snapshot-file> <sql-file>...   # regenerate snapshot

Output lines (parsed by cross_check.sh): CHANGED/REMOVED/NEW/OK.
Functions that build no json_build_object (scalar/table returns) are not snapshotted.
"""
import re
import sys

FUNC_RE = re.compile(r"create\s+or\s+replace\s+function\s+(?:public\.)?(\w+)", re.I)
KEY_RE = re.compile(r"'([A-Za-z0-9_]+)'\Z")


def jbo_keys(body: str) -> set:
    """Collect top-level string-literal keys of every json_build_object(...) in body."""
    keys = set()
    pos = 0
    while True:
        m = re.search(r"jsonb?_build_object\s*\(", body[pos:], re.I)
        if not m:
            break
        i = pos + m.end()
        depth, in_str = 1, False
        args, cur = [], ""
        while i < len(body) and depth > 0:
            c = body[i]
            if in_str:
                cur += c
                if c == "'":
                    if i + 1 < len(body) and body[i + 1] == "'":  # escaped ''
                        cur += "'"
                        i += 1
                    else:
                        in_str = False
            elif c == "'":
                in_str = True
                cur += c
            elif c == "(":
                depth += 1
                cur += c
            elif c == ")":
                depth -= 1
                if depth == 0:
                    if cur.strip():
                        args.append(cur.strip())
                else:
                    cur += c
            elif c == "," and depth == 1:
                args.append(cur.strip())
                cur = ""
            else:
                cur += c
            i += 1
        for k in range(0, len(args), 2):  # keys sit at even arg positions
            hit = KEY_RE.match(args[k])
            if hit:
                keys.add(hit.group(1))
        pos = pos + m.end()
    return keys


def extract(sql_files):
    contracts = {}
    for path in sql_files:
        try:
            text = open(path, encoding="utf-8", errors="replace").read()
        except OSError:
            print(f"WARN unreadable SQL file skipped: {path}", file=sys.stderr)
            continue
        marks = list(FUNC_RE.finditer(text))
        for idx, m in enumerate(marks):
            name = m.group(1)
            if not name.startswith("rpc_"):
                continue
            end = marks[idx + 1].start() if idx + 1 < len(marks) else len(text)
            keys = jbo_keys(text[m.start():end])
            if keys:
                contracts[name] = keys  # later definition wins (deploy order)
    return contracts


def load_snapshot(path):
    snap = {}
    try:
        for line in open(path, encoding="utf-8"):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            name, _, rest = line.partition(":")
            snap[name.strip()] = set(k for k in rest.strip().split(",") if k)
    except OSError:
        pass
    return snap


def main():
    if len(sys.argv) < 4 or sys.argv[1] not in ("check", "update"):
        print(__doc__)
        return 2
    mode, snap_path, sql_files = sys.argv[1], sys.argv[2], sys.argv[3:]
    current = extract(sql_files)

    if mode == "update":
        with open(snap_path, "w", encoding="utf-8") as f:
            f.write("# rpc_* return-contract snapshot (json_build_object keys). \n")
            f.write("# Generated by scripts/contract_snapshot.py update — do not edit by hand.\n")
            for name in sorted(current):
                f.write(f"{name}: {','.join(sorted(current[name]))}\n")
        print(f"OK: snapshot written — {len(current)} rpc contracts")
        return 0

    snap = load_snapshot(snap_path)
    if not snap:
        print(f"NEW snapshot missing/empty at {snap_path} — run update mode")
        return 1
    drift = 0
    for name in sorted(set(snap) | set(current)):
        if name not in current:
            print(f"REMOVED {name} (was: {','.join(sorted(snap[name]))})")
            drift += 1
        elif name not in snap:
            print(f"NEW {name}: {','.join(sorted(current[name]))}")
        elif snap[name] != current[name]:
            plus = ",".join(sorted(current[name] - snap[name])) or "-"
            minus = ",".join(sorted(snap[name] - current[name])) or "-"
            print(f"CHANGED {name}: +[{plus}] -[{minus}]")
            drift += 1
    if drift == 0:
        print(f"OK: {len(current)} rpc return-contracts match snapshot")
    return 1 if drift else 0


if __name__ == "__main__":
    sys.exit(main())
